spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/labo/micro-perio/config
server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'